from pathlib import Path

ROOT = Path("upstream/trakt_simplified_chinese/src")


def read(path):
    return (ROOT / path).read_text(encoding="utf-8")


def write(path, text):
    (ROOT / path).write_text(text, encoding="utf-8")


# One owner for translation scope/cache behavior. Do not patch the upstream
# helper with generated helper declarations: that was the source of the
# repeated-binding failures in previous runs.
policy = '''const CN_COUNTRIES = new Set(["cn", "hk", "tw", "sg", "mo"]);

export function isChineseProduction(ref) {
    const language = String(ref?.language ?? "").trim().toLowerCase();
    const raw = Array.isArray(ref?.country) ? ref.country : [ref?.country];
    const countries = raw
        .flatMap((value) => String(value ?? "").split(/[,|\\s]+/))
        .map((value) => value.trim().toLowerCase())
        .filter(Boolean);
    return language === "zh" || countries.some((country) => CN_COUNTRIES.has(country));
}

export function shouldTranslateMedia(ref, argument = globalThis.$ctx?.argument ?? {}) {
    const engine = String(argument.translationEngine ?? "google").trim().toLowerCase();
    const scope = String(argument.translationScope ?? "all").trim().toLowerCase();
    if (engine == "off" || scope === "off") return false;
    return scope !== "chinese_only" || isChineseProduction(ref);
}
'''
write("shared/translation-scope-policy.mjs", policy)

helper_path = "shared/trakt-translation-helper.mjs"
helper = read(helper_path)

# The upstream file currently uses namespace imports. Anchor to that exact
# import, not to a guessed named import. Re-running never creates duplicates.
policy_import = 'import { shouldTranslateMedia } from "./translation-scope-policy.mjs";\n'
if policy_import not in helper:
    anchor = 'import * as cacheUtils from "../utils/cache.mjs";\n'
    if anchor not in helper:
        raise SystemExit("Stable upstream anchor missing: cacheUtils namespace import")
    helper = helper.replace(anchor, anchor + policy_import, 1)

# Remove any legacy declarations from older repository revisions. No new
# legacy declarations are ever generated by this script.
for name in ("isChineseProductionRef", "shouldTranslateMediaRef"):
    marker = f"function {name}"
    while marker in helper:
        start = helper.find(marker)
        brace = helper.find("{", start)
        if brace < 0:
            raise SystemExit(f"Malformed legacy declaration: {name}")
        depth = 0
        quote = None
        escaped = False
        end = None
        for i in range(brace, len(helper)):
            ch = helper[i]
            if quote:
                if escaped:
                    escaped = False
                elif ch == "\\":
                    escaped = True
                elif ch == quote:
                    quote = None
                continue
            if ch in ("'", '"', "`"):
                quote = ch
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
        if end is None:
            raise SystemExit(f"Unbalanced legacy declaration: {name}")
        line_start = helper.rfind("\n", 0, start) + 1
        line_end = helper.find("\n", end)
        line_end = len(helper) if line_end < 0 else line_end + 1
        helper = helper[:line_start] + helper[line_end:]

# Build episode refs with the parent show's language/country so the same scope
# policy applies to episode lists without an extra Trakt request.
old_episode = '''        availableTranslations: commonUtils.isArray(episode.available_translations) ? episode.available_translations : null,
    };'''
new_episode = '''        availableTranslations: commonUtils.isArray(episode.available_translations) ? episode.available_translations : null,
        language: item?.show?.language ?? null,
        country: item?.show?.country ?? null,
    };'''
if old_episode in helper and new_episode not in helper:
    helper = helper.replace(old_episode, new_episode, 1)

# Filter the refs before any cache read/write or translation API call. This is
# the important performance and correctness boundary: a non-Chinese title in
# chinese_only mode neither consumes an old translation cache entry nor makes
# a remote translation request.
old = '    const refsByType = collectMediaRefs(items, MEDIA_CONFIG);\n'
new = '''    const refsByType = collectMediaRefs(items, MEDIA_CONFIG);
    const translationRefsByType = Object.fromEntries(
        Object.entries(refsByType).map(([type, refs]) => [type, refs.filter((ref) => shouldTranslateMedia(ref))]),
    );
'''
if old in helper and new not in helper:
    helper = helper.replace(old, new, 1)
elif new not in helper:
    raise SystemExit("Stable translation refs boundary not found")

helper = helper.replace("hydrateFromBackend(cache, refsByType, MEDIA_CONFIG, backendState)", "hydrateFromBackend(cache, translationRefsByType, MEDIA_CONFIG, backendState)")
helper = helper.replace("fetchBulkTranslationsForMissing(cache, refsByType, backendState)", "fetchBulkTranslationsForMissing(cache, translationRefsByType, backendState)")
helper = helper.replace("getMissingRefs(cache, mediaType, refsByType[mediaType])", "getMissingRefs(cache, mediaType, translationRefsByType[mediaType])")

old_apply = '                applyTranslationFn(target, getCachedTranslation(cache, mediaType, ref), ref);'
new_apply = '                if (shouldTranslateMedia(ref)) applyTranslationFn(target, getCachedTranslation(cache, mediaType, ref), ref);'
if old_apply in helper and new_apply not in helper:
    helper = helper.replace(old_apply, new_apply, 1)

write(helper_path, helper)
print("Translation scope/cache layer installed using the current upstream helper structure.")
